# config_gpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-standard-8
        acceleratorType: NVIDIA_TESLA_P100
        acceleratorCount: 1
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/adroit-chemist-447918-n1/training_image:latest
