site_name: danish_to_english_llm
site_author: Group 26
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - Model: model.md
  - Train: train.md
  - Data: data.md
  - API: api.md
