name: DVC Workflow

on:
  pull_request:
    branches:
    - main
    paths:
    - '**/*.dvc'
    - '.dvc/**'
jobs:
  run_data_trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        pip install -r requirements_dev.txt
        pip install -r requirements.txt
        pip list

    - name: Auth with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Pull data
      run: |
        dvc pull --no-run-cache
