name: Tests & Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt
          pip install -r requirements.txt
          pip list

      - name: Ruff check
        run: ruff check . --fix

      - name: Ruff format
        run: ruff format .

      - name: Mypy check
        continue-on-error: true  # Makes mypy checks optional
        run: mypy src/

  test:
    needs: format
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Cache dataset files
        uses: actions/cache@v4
        with:
          path: |
            data/raw
            data/processed
            ~/.cache/huggingface
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-dataset-v1
          restore-keys: |
            ${{ runner.os }}-python-${{ matrix.python-version }}-dataset-
            ${{ runner.os }}-python-dataset-

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip install coverage[toml]
          pip install -r requirements_dev.txt
          pip list
      - name: Install project
        run: pip install -e .

      - name: Run tests & coverage
        run: |
          coverage run --source=danish_to_english_llm -m pytest tests/unit_tests/
          coverage report -m


  build:
    needs: test
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with google cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build container image
        run: gcloud builds submit --config cloudbuild_train.yaml
